### ISSUE TITLE
Inconsistency Bowen cooling 1D vs 3D

### ISSUE THREAD

**Issue by MatsEsseldeurs** [lsiess/phantom#6]
The 1D solution of a wind model with Bowen cooling activated gives different results than the 3D SPH solution of the same model, when plotting the gas temperature in the radial direction (see image). This results are still consistent for other cooling schemes (H1 cooling I checked).
![Figure_1](https://github.com/user-attachments/assets/5ac8e860-26aa-415a-bd14-04414ff45092)

Here the .in and .setup files I used to create the image
[wind.in](https://github.com/user-attachments/files/16248461/wind.in.txt)
[wind.setup](https://github.com/user-attachments/files/16248462/wind.setup.txt)

**Comment by lsiess** [comment]
fixed
